import { StrictMode, useEffect, useMemo, useRef, useState, type ReactNode, type RefObject } from 'react'
import { createRoot } from 'react-dom/client'
import { runtimeAdapter } from '../../chrome/runtimeAdapter'
import type {
  AiClassificationResult,
  AiSettings,
  BookmarkItem,
  BookmarkNode,
  BookmarkScanResult,
  CleanupSuggestion,
} from '../../types/bookmarks'
import {
  MESSAGE_VERSION,
  type AiClassificationResponse,
  type AiSettingsResponse,
  type ApplyResponse,
  type OperationHistoryResult,
  type ScanResponse,
  type UndoResponse,
} from '../../types/messages'
import type { OperationBatch } from '../../types/operations'
import '../shared.css'

const SHOW_READ_ONLY_DIAGNOSTICS = false

function fullPath(node: BookmarkNode): string {
  return [...node.path, node.title || '(untitled)'].join(' / ')
}

function IssueCard({
  suggestion,
  result,
  selected,
  onToggle,
}: {
  suggestion: CleanupSuggestion
  result: BookmarkScanResult
  selected: boolean
  onToggle: () => void
}) {
  const keeper = suggestion.keepId
    ? result.nodes[result.indexes.byId[suggestion.keepId]]
    : null
  const destination = suggestion.targetFolderId
    ? result.nodes[result.indexes.byId[suggestion.targetFolderId]]
    : null
  const badgeLabel = suggestion.kind === 'move-bookmark'
    ? suggestion.source === 'ai' ? 'AI suggestion' : 'Move suggestion'
    : suggestion.kind === 'delete-empty-folder'
      ? 'Empty folder'
      : suggestion.duplicateType === 'exact' ? 'Exact duplicate' : 'Normalized duplicate'

  return (
    <article className={`issue-card ${selected ? 'issue-selected' : ''}`}>
      <div className="issue-heading">
        <span className={`badge ${suggestion.duplicateType === 'normalized' ? 'badge-caution' : ''} ${suggestion.kind === 'move-bookmark' ? 'badge-move' : ''}`}>
          {badgeLabel}
        </span>
        <span className="confidence">{Math.round(suggestion.confidence * 100)}% confidence</span>
      </div>
      <strong>{suggestion.before.title || '(untitled)'}</strong>
      <span className="path">{fullPath(suggestion.before)}</span>
      {suggestion.before.type === 'bookmark' && <code>{suggestion.before.url}</code>}
      {keeper && <p className="keeper">Keep: {fullPath(keeper)}</p>}
      {destination && <p className="destination">Move to: {fullPath(destination)}</p>}
      {suggestion.reasons.map((reason) => <p key={reason}>{reason}</p>)}
      {suggestion.source === 'ai' && <span className="ai-model">Generated by {suggestion.model}</span>}
      <label className="select-control">
        <input type="checkbox" checked={selected} onChange={onToggle} />
        Include in review batch
      </label>
    </article>
  )
}

function BatchSummary({ batch, undoing, onUndo, undoButtonRef }: {
  batch: OperationBatch
  undoing: boolean
  onUndo: () => void
  undoButtonRef: RefObject<HTMLButtonElement | null>
}) {
  const succeeded = batch.operations.filter((operation) => operation.status === 'success').length
  const failed = batch.operations.filter((operation) => operation.status === 'failed').length
  const skipped = batch.operations.filter((operation) => operation.status === 'skipped').length
  const uncertain = batch.operations.filter((operation) => operation.status === 'executing').length
  const canUndo = batch.kind === 'apply'
    && !batch.undoneByBatchId
    && batch.status !== 'running'
    && batch.status !== 'interrupted'
    && batch.status !== 'undone'
    && batch.status !== 'undo-partial'
    && batch.operations.some((operation) => operation.status === 'success' && operation.undoStatus !== 'success')
  const issues = batch.operations.filter((operation) =>
    operation.error || operation.undoError,
  )

  return (
    <section className="card batch-card" aria-live="polite">
      <div>
        <span className="eyebrow">Latest {batch.kind} batch</span>
        <h2 className="batch-title">{batch.status.replace('-', ' ')}</h2>
        <p>{succeeded} succeeded · {failed} failed · {skipped} skipped{uncertain ? ` · ${uncertain} needs verification` : ''}</p>
        {batch.status === 'interrupted' && (
          <p className="warning-text">The worker stopped during this batch. Verify uncertain items before making more changes.</p>
        )}
        {issues.length > 0 && (
          <ul className="batch-results">
            {issues.map((operation) => (
              <li key={operation.id}>{operation.before.title || operation.targetId}: {operation.undoError ?? operation.error}</li>
            ))}
          </ul>
        )}
      </div>
      {canUndo && (
        <button ref={undoButtonRef} type="button" className="secondary-button" onClick={onUndo} disabled={undoing}>
          {undoing ? 'Undoing…' : 'Undo latest batch'}
        </button>
      )}
    </section>
  )
}

function OperationHistory({ batches }: { batches: OperationBatch[] }) {
  if (batches.length === 0) return null

  return (
    <details className="card history-card">
      <summary>
        <span>
          <span className="eyebrow">Operation history</span>
          <strong>{batches.length} earlier batch{batches.length === 1 ? '' : 'es'}</strong>
        </span>
        <span className="result-count">Stored locally</span>
      </summary>
      <ol className="history-list">
        {batches.map((batch) => {
          const succeeded = batch.operations.filter((operation) => operation.status === 'success').length
          const issues = batch.operations.length - succeeded
          return (
            <li key={batch.id}>
              <span>
                <strong className="history-status">{batch.kind} · {batch.status.replace('-', ' ')}</strong>
                <small>{new Date(batch.createdAt).toLocaleString()}</small>
              </span>
              <span>
                {succeeded} succeeded{issues ? ` · ${issues} not applied` : ''}
                {batch.undoneByBatchId ? ' · undo recorded' : ''}
              </span>
            </li>
          )
        })}
      </ol>
      <p className="history-note">For safety, only the newest eligible batch can be undone.</p>
    </details>
  )
}

function ConfirmationDialog({
  busy,
  labelledBy,
  describedBy,
  onCancel,
  children,
}: {
  busy: boolean
  labelledBy: string
  describedBy: string
  onCancel: () => void
  children: ReactNode
}) {
  const dialogRef = useRef<HTMLElement>(null)

  useEffect(() => {
    const previousOverflow = document.body.style.overflow
    document.body.style.overflow = 'hidden'
    dialogRef.current?.querySelector<HTMLElement>('button:not(:disabled)')?.focus()

    const handleKeyDown = (event: KeyboardEvent) => {
      if (event.key === 'Escape' && !busy) onCancel()
      if (event.key !== 'Tab') return

      const focusable = dialogRef.current?.querySelectorAll<HTMLElement>('button:not(:disabled)')
      if (!focusable?.length) return
      const first = focusable[0]
      const last = focusable[focusable.length - 1]
      if (event.shiftKey && document.activeElement === first) {
        event.preventDefault()
        last.focus()
      } else if (!event.shiftKey && document.activeElement === last) {
        event.preventDefault()
        first.focus()
      }
    }

    document.addEventListener('keydown', handleKeyDown)
    return () => {
      document.removeEventListener('keydown', handleKeyDown)
      document.body.style.overflow = previousOverflow
    }
  }, [busy, onCancel])

  return (
    <div
      className="modal-backdrop"
      onMouseDown={(event) => {
        if (event.target === event.currentTarget && !busy) onCancel()
      }}
    >
      <section
        ref={dialogRef}
        className="confirmation-modal"
        role="dialog"
        aria-modal="true"
        aria-labelledby={labelledBy}
        aria-describedby={describedBy}
      >
        {children}
      </section>
    </div>
  )
}

function ApplyConfirmation({
  suggestions,
  applying,
  onCancel,
  onConfirm,
}: {
  suggestions: CleanupSuggestion[]
  applying: boolean
  onCancel: () => void
  onConfirm: () => void
}) {
  const moves = suggestions.filter((suggestion) => suggestion.kind === 'move-bookmark').length
  const duplicateDeletions = suggestions.filter((suggestion) => suggestion.kind === 'delete-duplicate').length
  const emptyFolderDeletions = suggestions.filter((suggestion) => suggestion.kind === 'delete-empty-folder').length
  const deletionCount = duplicateDeletions + emptyFolderDeletions

  return (
    <ConfirmationDialog
      busy={applying}
      labelledBy="apply-confirmation-title"
      describedBy="apply-confirmation-description"
      onCancel={onCancel}
    >
      <span className="eyebrow">Final review</span>
      <h2 id="apply-confirmation-title">Apply {suggestions.length} reviewed change{suggestions.length === 1 ? '' : 's'}?</h2>
      <p id="apply-confirmation-description">
        A snapshot will be saved before anything changes. Every target will also be checked again.
      </p>
      <dl className="confirmation-summary">
        <div><dt>Bookmarks moved</dt><dd>{moves}</dd></div>
        <div><dt>Duplicates deleted</dt><dd>{duplicateDeletions}</dd></div>
        <div><dt>Empty folders deleted</dt><dd>{emptyFolderDeletions}</dd></div>
      </dl>
      {deletionCount > 0 && (
        <p className="confirmation-warning">
          This batch includes {deletionCount} deletion{deletionCount === 1 ? '' : 's'}. You can undo the latest completed batch.
        </p>
      )}
      <div className="modal-actions">
        <button type="button" className="secondary-button" onClick={onCancel} disabled={applying}>
          Cancel
        </button>
        <button type="button" className={deletionCount > 0 ? 'danger-button' : ''} onClick={onConfirm} disabled={applying}>
          {applying ? 'Applying…' : `Apply ${suggestions.length} change${suggestions.length === 1 ? '' : 's'}`}
        </button>
      </div>
    </ConfirmationDialog>
  )
}

function UndoConfirmation({
  batch,
  undoing,
  onCancel,
  onConfirm,
}: {
  batch: OperationBatch
  undoing: boolean
  onCancel: () => void
  onConfirm: () => void
}) {
  const reversible = batch.operations.filter((operation) =>
    operation.status === 'success' && operation.undoStatus !== 'success',
  )
  const moves = reversible.filter((operation) => operation.kind === 'move').length
  const bookmarks = reversible.filter((operation) =>
    operation.kind === 'delete' && operation.before.type === 'bookmark',
  ).length
  const folders = reversible.filter((operation) =>
    operation.kind === 'delete' && operation.before.type === 'folder',
  ).length

  return (
    <ConfirmationDialog
      busy={undoing}
      labelledBy="undo-confirmation-title"
      describedBy="undo-confirmation-description"
      onCancel={onCancel}
    >
      <span className="eyebrow">Confirm undo</span>
      <h2 id="undo-confirmation-title">Undo {reversible.length} completed change{reversible.length === 1 ? '' : 's'}?</h2>
      <p id="undo-confirmation-description">
        Only successful operations from the latest batch will be reversed. Failed and skipped operations will remain unchanged.
      </p>
      <dl className="confirmation-summary">
        <div><dt>Bookmarks moved back</dt><dd>{moves}</dd></div>
        <div><dt>Bookmarks restored</dt><dd>{bookmarks}</dd></div>
        <div><dt>Folders restored</dt><dd>{folders}</dd></div>
      </dl>
      <p className="confirmation-warning">
        If a bookmark changed again after this batch, that item may be skipped to protect the newer change.
      </p>
      <div className="modal-actions">
        <button type="button" className="secondary-button" onClick={onCancel} disabled={undoing}>
          Cancel
        </button>
        <button type="button" onClick={onConfirm} disabled={undoing}>
          {undoing ? 'Undoing…' : 'Undo latest batch'}
        </button>
      </div>
    </ConfirmationDialog>
  )
}

function BookmarkRow({ bookmark }: { bookmark: BookmarkItem }) {
  return (
    <li className="bookmark-row">
      <div>
        <strong>{bookmark.title || '(untitled)'}</strong>
        <span className="path">{fullPath(bookmark)}</span>
      </div>
      <a href={bookmark.url} target="_blank" rel="noreferrer">{bookmark.domain || bookmark.url}</a>
    </li>
  )
}

function formatDepths(depths: Record<string, number>): string {
  const entries = Object.entries(depths).sort(([left], [right]) => Number(left) - Number(right))
  return entries.length ? entries.map(([depth, count]) => `D${depth}: ${count}`).join(' · ') : 'None'
}

function Diagnostics({ result }: { result: BookmarkScanResult }) {
  const diagnostics = result.diagnostics
  const classification = diagnostics.classification

  return (
    <details className="card diagnostics-card" open>
      <summary>
        <span>
          <span className="eyebrow">Read-only diagnostics</span>
          <strong>Why suggestions were included or filtered</strong>
        </span>
        <code>{diagnostics.analyzerBuild}</code>
      </summary>
      <p>This section contains counts only. It does not expose bookmark URLs or change the library.</p>
      <dl className="diagnostics-grid">
        <div><dt>Root nodes</dt><dd>{diagnostics.rootNodes}</dd></div>
        <div><dt>Protected folders</dt><dd>{diagnostics.protectedFolders}</dd></div>
        <div><dt>User folders</dt><dd>{diagnostics.userFolders}</dd></div>
        <div><dt>Candidate folders</dt><dd>{classification.candidateFolders}</dd></div>
        <div><dt>Bookmarks visited</dt><dd>{classification.bookmarksVisited}</dd></div>
        <div><dt>Eligible for classification</dt><dd>{classification.eligibleForClassification}</dd></div>
        <div><dt>Already in named folders</dt><dd>{classification.bookmarksAlreadyInMeaningfulFolder}</dd></div>
        <div><dt>Cleanup targets skipped</dt><dd>{classification.skippedCleanupTargets}</dd></div>
        <div><dt>Content-platform candidates</dt><dd>{classification.eligibleContentPlatformBookmarks}</dd></div>
        <div><dt>With domain candidates</dt><dd>{classification.bookmarksWithDomainCandidates}</dd></div>
        <div><dt>With keyword candidates</dt><dd>{classification.bookmarksWithKeywordCandidates}</dd></div>
        <div><dt>No qualifying destination</dt><dd>{classification.skippedNoCandidate}</dd></div>
        <div><dt>Top-score ties</dt><dd>{classification.skippedTopScoreTie}</dd></div>
        <div><dt>Current folder as good or better</dt><dd>{classification.skippedCurrentPlacementAsGoodOrBetter}</dd></div>
        <div><dt>Move suggestions created</dt><dd>{classification.suggestionsCreated}</dd></div>
      </dl>
      <div className="depth-diagnostics">
        <span><strong>Bookmarks by depth</strong>{formatDepths(diagnostics.bookmarksByDepth)}</span>
        <span><strong>Folders by depth</strong>{formatDepths(diagnostics.foldersByDepth)}</span>
      </div>
    </details>
  )
}

function AiSettingsPanel({
  settings,
  apiKey,
  saving,
  running,
  onSettingsChange,
  onApiKeyChange,
  onSave,
  onClearKey,
  onRun,
}: {
  settings: AiSettings
  apiKey: string
  saving: boolean
  running: boolean
  onSettingsChange: (settings: AiSettings) => void
  onApiKeyChange: (value: string) => void
  onSave: () => void
  onClearKey: () => void
  onRun: () => void
}) {
  return (
    <details className="card ai-settings-card" open={!settings.hasApiKey}>
      <summary>
        <span>
          <span className="eyebrow">Optional AI classification</span>
          <strong>{settings.enabled ? 'Enabled' : 'Disabled'} · {settings.model}</strong>
        </span>
        <span className="result-count">OpenAI · Bring your own key</span>
      </summary>
      <p>
        AI only creates reviewable suggestions for existing folders. It never changes bookmarks automatically.
        Full URLs are never sent.
      </p>
      <div className="ai-settings-grid">
        <label className="toggle-field">
          <input
            type="checkbox"
            checked={settings.enabled}
            onChange={(event) => onSettingsChange({ ...settings, enabled: event.target.checked })}
          />
          Enable AI classification
        </label>
        <label>
          <span>Privacy mode</span>
          <select
            value={settings.privacyMode}
            onChange={(event) => onSettingsChange({
              ...settings,
              privacyMode: event.target.value as AiSettings['privacyMode'],
            })}
          >
            <option value="domain-only">Domain only</option>
            <option value="title-and-domain">Title, domain, and current folder</option>
          </select>
        </label>
        <label>
          <span>Model</span>
          <input
            value={settings.model}
            onChange={(event) => onSettingsChange({ ...settings, model: event.target.value })}
            placeholder="gpt-5-mini"
          />
        </label>
        <label>
          <span>OpenAI API key</span>
          <input
            type="password"
            value={apiKey}
            onChange={(event) => onApiKeyChange(event.target.value)}
            placeholder={settings.hasApiKey ? 'Saved locally — enter a new key to replace it' : 'sk-…'}
            autoComplete="off"
          />
        </label>
      </div>
      <p className="ai-privacy-note">
        The key is stored in Chrome local extension storage on this browser. For a public release, route requests through a server instead of distributing an application-owned key.
      </p>
      <div className="ai-actions">
        {settings.hasApiKey && (
          <button type="button" className="secondary-button" onClick={onClearKey} disabled={saving || running}>
            Remove saved key
          </button>
        )}
        <button type="button" className="secondary-button" onClick={onSave} disabled={saving || running}>
          {saving ? 'Saving…' : 'Save AI settings'}
        </button>
        <button type="button" onClick={onRun} disabled={!settings.enabled || !settings.hasApiKey || saving || running}>
          {running ? 'Running AI scan…' : 'Run AI classification'}
        </button>
      </div>
    </details>
  )
}

export function Manager() {
  const [result, setResult] = useState<BookmarkScanResult | null>(null)
  const [query, setQuery] = useState('')
  const [selectedIds, setSelectedIds] = useState<Set<string>>(() => new Set())
  const [history, setHistory] = useState<OperationBatch[]>([])
  const [loading, setLoading] = useState(false)
  const [aiRunning, setAiRunning] = useState(false)
  const [aiSaving, setAiSaving] = useState(false)
  const [aiApiKey, setAiApiKey] = useState('')
  const [aiSettings, setAiSettings] = useState<AiSettings>({
    enabled: false,
    model: 'gpt-5-mini',
    privacyMode: 'domain-only',
    hasApiKey: false,
  })
  const [applying, setApplying] = useState(false)
  const [undoing, setUndoing] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [pendingSuggestions, setPendingSuggestions] = useState<CleanupSuggestion[] | null>(null)
  const [pendingUndoBatch, setPendingUndoBatch] = useState<OperationBatch | null>(null)
  const reviewButtonRef = useRef<HTMLButtonElement>(null)
  const undoButtonRef = useRef<HTMLButtonElement>(null)
  const latestBatch = history[0] ?? null

  useEffect(() => {
    void runtimeAdapter
      .send<OperationHistoryResult>({ version: MESSAGE_VERSION, type: 'GET_OPERATION_HISTORY' })
      .then((response) => {
        if (response.ok) setHistory(response.data)
      })
      .catch(() => setError('Saved operation history is temporarily unavailable. Scanning is still safe.'))
  }, [])

  useEffect(() => {
    void runtimeAdapter
      .send<AiSettingsResponse>({ version: MESSAGE_VERSION, type: 'GET_AI_SETTINGS' })
      .then((response) => {
        if (response.ok) setAiSettings(response.data)
      })
      .catch(() => setError('AI settings are temporarily unavailable. Local scanning still works.'))
  }, [])

  useEffect(() => {
    if (!pendingSuggestions) reviewButtonRef.current?.focus()
  }, [pendingSuggestions])

  useEffect(() => {
    if (!pendingUndoBatch) undoButtonRef.current?.focus()
  }, [pendingUndoBatch])

  const bookmarks = useMemo(() => {
    if (!result) return []
    const normalizedQuery = query.trim().toLowerCase()
    return result.nodes.filter((node): node is BookmarkItem => {
      if (node.type !== 'bookmark') return false
      if (!normalizedQuery) return true
      return [node.title, node.url, node.domain, node.path.join(' ')]
        .some((value) => value.toLowerCase().includes(normalizedQuery))
    })
  }, [query, result])

  const duplicateSuggestions = result?.suggestions.filter((item) => item.kind === 'delete-duplicate') ?? []
  const emptyFolderSuggestions = result?.suggestions.filter((item) => item.kind === 'delete-empty-folder') ?? []
  const localClassificationSuggestions = result?.suggestions.filter((item) =>
    item.kind === 'move-bookmark' && item.source !== 'ai',
  ) ?? []
  const aiClassificationSuggestions = result?.suggestions.filter((item) =>
    item.kind === 'move-bookmark' && item.source === 'ai',
  ) ?? []
  const classificationSuggestions = [...localClassificationSuggestions, ...aiClassificationSuggestions]
  const cleanupSuggestionCount = duplicateSuggestions.length + emptyFolderSuggestions.length
  const aiSummary = result && 'ai' in result ? (result as AiClassificationResult).ai : null

  const saveAiSettings = async () => {
    setAiSaving(true)
    setError(null)
    try {
      const response = await runtimeAdapter.send<AiSettingsResponse>({
        version: MESSAGE_VERSION,
        type: 'SAVE_AI_SETTINGS',
        settings: {
          enabled: aiSettings.enabled,
          model: aiSettings.model,
          privacyMode: aiSettings.privacyMode,
          apiKey: aiApiKey || undefined,
        },
      })
      if (response.ok) {
        setAiSettings(response.data)
        setAiApiKey('')
      } else setError(response.error.message)
    } catch (settingsError) {
      setError(settingsError instanceof Error ? settingsError.message : 'AI settings could not be saved.')
    } finally {
      setAiSaving(false)
    }
  }

  const runAiClassification = async () => {
    setAiRunning(true)
    setError(null)
    try {
      const response = await runtimeAdapter.send<AiClassificationResponse>({
        version: MESSAGE_VERSION,
        type: 'CLASSIFY_WITH_AI',
      })
      if (response.ok) {
        setResult(response.data)
        setSelectedIds(new Set())
      } else setError(response.error.message)
    } catch (aiError) {
      setError(aiError instanceof Error ? aiError.message : 'AI classification could not be completed.')
    } finally {
      setAiRunning(false)
    }
  }

  const clearAiKey = async () => {
    setAiSaving(true)
    setError(null)
    try {
      const response = await runtimeAdapter.send<AiSettingsResponse>({
        version: MESSAGE_VERSION,
        type: 'SAVE_AI_SETTINGS',
        settings: {
          enabled: false,
          model: aiSettings.model,
          privacyMode: aiSettings.privacyMode,
          clearApiKey: true,
        },
      })
      if (response.ok) {
        setAiSettings(response.data)
        setAiApiKey('')
      } else setError(response.error.message)
    } catch (settingsError) {
      setError(settingsError instanceof Error ? settingsError.message : 'The saved AI key could not be removed.')
    } finally {
      setAiSaving(false)
    }
  }

  const scan = async () => {
    setLoading(true)
    setError(null)
    try {
      const response = await runtimeAdapter.send<ScanResponse>({ version: MESSAGE_VERSION, type: 'SCAN_BOOKMARKS' })
      if (response.ok) {
        setResult(response.data)
        setSelectedIds(new Set())
      }
      else setError(response.error.message)
    } catch (scanError) {
      setError(scanError instanceof Error ? scanError.message : 'The extension worker is unavailable. Reload and try again.')
    } finally {
      setLoading(false)
    }
  }

  const toggleSuggestion = (id: string) => {
    setSelectedIds((current) => {
      const next = new Set(current)
      if (next.has(id)) next.delete(id)
      else next.add(id)
      return next
    })
  }

  const openApplyConfirmation = () => {
    if (!result || selectedIds.size === 0) return
    setPendingSuggestions(result.suggestions.filter((suggestion) => selectedIds.has(suggestion.id)))
  }

  const applySelected = async () => {
    if (!pendingSuggestions) return
    const suggestions = pendingSuggestions
    setApplying(true)
    setError(null)
    try {
      const response = await runtimeAdapter.send<ApplyResponse>({
        version: MESSAGE_VERSION,
        type: 'APPLY_SUGGESTIONS',
        suggestions,
      })
      if (response.ok) {
        setHistory((current) => [response.data, ...current.filter((batch) => batch.id !== response.data.id)])
        await scan()
      } else {
        setError(response.error.message)
      }
    } catch (applyError) {
      setError(applyError instanceof Error ? applyError.message : 'The operation batch could not be applied.')
    } finally {
      setApplying(false)
      setPendingSuggestions(null)
    }
  }

  const undoLatest = async () => {
    if (!pendingUndoBatch) return
    setUndoing(true)
    setError(null)
    try {
      const response = await runtimeAdapter.send<UndoResponse>({ version: MESSAGE_VERSION, type: 'UNDO_LATEST_BATCH' })
      if (response.ok) {
        setHistory((current) => [
          response.data.undoBatch,
          response.data.sourceBatch,
          ...current.filter((batch) =>
            batch.id !== response.data.undoBatch.id && batch.id !== response.data.sourceBatch.id,
          ),
        ])
        await scan()
      } else {
        setError(response.error.message)
      }
    } catch (undoError) {
      setError(undoError instanceof Error ? undoError.message : 'The latest batch could not be undone.')
    } finally {
      setUndoing(false)
      setPendingUndoBatch(null)
    }
  }

  return (
    <main className="shell">
      <header className="page-header">
        <div>
          <span className="eyebrow">v0.2 · Optional AI classification</span>
          <h1>Bookmark Tidy</h1>
          <p>Scanning is read-only. Only suggestions you select and explicitly confirm can modify bookmarks.</p>
        </div>
        <button type="button" onClick={scan} disabled={loading || aiRunning}>
          {loading ? 'Scanning…' : result ? 'Scan again' : 'Scan bookmarks'}
        </button>
      </header>

      {error && <p className="alert error" role="alert">{error}</p>}
      <AiSettingsPanel
        settings={aiSettings}
        apiKey={aiApiKey}
        saving={aiSaving}
        running={aiRunning}
        onSettingsChange={setAiSettings}
        onApiKeyChange={setAiApiKey}
        onSave={saveAiSettings}
        onClearKey={clearAiKey}
        onRun={runAiClassification}
      />
      {latestBatch && (
        <BatchSummary
          batch={latestBatch}
          undoing={undoing}
          onUndo={() => setPendingUndoBatch(latestBatch)}
          undoButtonRef={undoButtonRef}
        />
      )}
      <OperationHistory batches={history.slice(1)} />

      {!result ? (
        <section className="card empty-state">
          <div className="empty-icon" aria-hidden="true">✓</div>
          <h2>Analysis stays separate from changes</h2>
          <p>The scanner only reads your bookmark tree. Every selected change is revalidated and snapshotted before execution.</p>
        </section>
      ) : (
        <>
          <section className="stats stats-five" aria-label="Library overview">
            <div className="stat"><strong>{result.summary.bookmarks}</strong><span>Bookmarks</span></div>
            <div className="stat"><strong>{result.summary.folders}</strong><span>Folders</span></div>
            <div className="stat stat-accent"><strong>{result.summary.duplicateGroups}</strong><span>Duplicate groups</span></div>
            <div className="stat stat-accent"><strong>{result.summary.emptyFolders}</strong><span>Empty folders</span></div>
            <div className="stat stat-accent"><strong>{result.summary.classificationSuggestions}</strong><span>Folder suggestions</span></div>
          </section>

          {SHOW_READ_ONLY_DIAGNOSTICS && <Diagnostics result={result} />}

          {aiSummary && (
            <section className="card ai-summary" aria-live="polite">
              <div>
                <span className="eyebrow">AI scan complete</span>
                <h2>{aiSummary.suggestionsCreated} AI suggestion{aiSummary.suggestionsCreated === 1 ? '' : 's'}</h2>
                <p>{aiSummary.bookmarksSent} bookmark{aiSummary.bookmarksSent === 1 ? '' : 's'} sent using {aiSummary.privacyMode.replaceAll('-', ' ')} mode.</p>
              </div>
              <span className="read-only-pill">Review required</span>
            </section>
          )}

          <section className="card section-card">
            <div className="section-heading">
              <div>
                <span className="eyebrow">Cleanup findings</span>
                <h2>{cleanupSuggestionCount} cleanup suggestions</h2>
              </div>
              <span className="read-only-pill">Review required</span>
            </div>

            {cleanupSuggestionCount === 0 ? (
              <p>No duplicates or empty folders found.</p>
            ) : (
              <div className="issues-grid">
                {duplicateSuggestions.map((suggestion) => (
                  <IssueCard
                    key={suggestion.id}
                    suggestion={suggestion}
                    result={result}
                    selected={selectedIds.has(suggestion.id)}
                    onToggle={() => toggleSuggestion(suggestion.id)}
                  />
                ))}
                {emptyFolderSuggestions.map((suggestion) => (
                  <IssueCard
                    key={suggestion.id}
                    suggestion={suggestion}
                    result={result}
                    selected={selectedIds.has(suggestion.id)}
                    onToggle={() => toggleSuggestion(suggestion.id)}
                  />
                ))}
              </div>
            )}
          </section>

          <section className="card section-card">
            <div className="section-heading">
              <div>
                <span className="eyebrow">Local and AI classification</span>
                <h2>{classificationSuggestions.length} organization suggestions</h2>
              </div>
              <span className="read-only-pill">{aiClassificationSuggestions.length} AI · {localClassificationSuggestions.length} local</span>
            </div>
            {classificationSuggestions.length === 0 ? (
              <p>No high-confidence moves to existing folders were found.</p>
            ) : (
              <div className="issues-grid">
                {classificationSuggestions.map((suggestion) => (
                  <IssueCard
                    key={suggestion.id}
                    suggestion={suggestion}
                    result={result}
                    selected={selectedIds.has(suggestion.id)}
                    onToggle={() => toggleSuggestion(suggestion.id)}
                  />
                ))}
              </div>
            )}
          </section>

          {result.suggestions.length > 0 && (
            <div className="review-bar sticky-review">
              <div>
                <strong>{selectedIds.size} selected</strong>
                <span>Nothing changes until you confirm. Every target is checked again first.</span>
              </div>
              <button ref={reviewButtonRef} type="button" onClick={openApplyConfirmation} disabled={selectedIds.size === 0 || applying || loading}>
                Apply reviewed changes
              </button>
            </div>
          )}

          <section className="card section-card">
            <div className="section-heading">
              <div>
                <span className="eyebrow">All bookmarks</span>
                <h2>Search the scanned library</h2>
              </div>
              <span className="result-count">{bookmarks.length} results</span>
            </div>
            <label className="search-field">
              <span className="sr-only">Search bookmarks</span>
              <input
                type="search"
                value={query}
                onChange={(event) => setQuery(event.target.value)}
                placeholder="Search title, URL, domain, or path…"
              />
            </label>
            {bookmarks.length ? (
              <ul className="bookmark-list">
                {bookmarks.map((bookmark) => <BookmarkRow key={bookmark.id} bookmark={bookmark} />)}
              </ul>
            ) : <p>No bookmarks match this search.</p>}
          </section>
        </>
      )}

      {pendingSuggestions && (
        <ApplyConfirmation
          suggestions={pendingSuggestions}
          applying={applying}
          onCancel={() => setPendingSuggestions(null)}
          onConfirm={applySelected}
        />
      )}
      {pendingUndoBatch && (
        <UndoConfirmation
          batch={pendingUndoBatch}
          undoing={undoing}
          onCancel={() => setPendingUndoBatch(null)}
          onConfirm={undoLatest}
        />
      )}
    </main>
  )
}

createRoot(document.getElementById('root')!).render(
  <StrictMode><Manager /></StrictMode>,
)
